from tokens import *

gml_keywords = {
	'begin': lambda _: LBraceToken(True),
	  'end': lambda _: RBraceToken(True),
	  'and': lambda _: AndToken(True),
	   'or': lambda _: OrToken(True),
	  'xor': lambda _: XorToken(True),
	  'not': lambda _: LogicNotToken(True),
	  'mod': lambda _: TK.INT_MOD,
	  'div': lambda _: TK.INT_DIV,
	  'new': lambda _: TK.NEW_OBJECT,

	'if': None,
	'then': None,
	'else': None,
	'while': None,
	'do': None,
	'for': None,
	'break': None,
	'continue': None,
	'with': None,
	'until': None,
	'repeat': None,
	'exit': None,
	'return': None,
	'switch': None,
	'case': None,
	'default': None,
	'var': None,
	'globalvar': None,
	'enum': None,
	'function': None,
	'try': None,
	'catch': None,
	'finally': None,
	'throw': None,
	'static': None,
	'delete': None,
	'constructor': None,

	# Not technically keywords but mightaswell here anyway
	     'true': lambda _: TK.TRUE,
	    'false': lambda _: TK.FALSE,
	     'self': lambda _: TK.SELF,
	    'other': lambda _: TK.OTHER,
	      'all': lambda _: TK.ALL,
	    'noone': lambda _: TK.NOONE,
	   'global': lambda _: TK.GLOBAL,
	'undefined': lambda _: TK.UNDEFINED,
}
